Dutch translation file added.
PhiTux/DailyTxT pull request #51
Opened 2024-11-14 09:01 UTC by mhartgring

I like your project so I have created a Dutch translation file for you.

(I hope I did this right, it has been a while since I created a PR)

2024-11-14 09:23 UTC, Stokkie64 requested changes
Thanks so much for your PR! It's really appreciated. 
I've added some small feedback suggestions. Mostly small things or subjective style points. I leave it up to you which you want to take with. :)

2024-11-14 09:23 UTC, Stokkie64 commented on client/src/lang/translations/nl.json
> +  "modal-history-title": "Geschiedens van geselecteerde dag",
Geschiedenis van de geselecteerde dag

2024-11-14 09:23 UTC, Stokkie64 commented on client/src/lang/translations/nl.json
> +  "update-available-client-version": "Huidig geinstalleerde versie",
geïnstalleerde

2024-11-14 09:23 UTC, Stokkie64 commented on client/src/lang/translations/nl.json
> +  "backup-codes-description-1": "Back-up codes werken als eenmalige wachtwoorden. Ze kunnen altijd worden gebruikt in plaats van het normale wachtwoord (bijvoorbeeld als je het vergeten bent), maar s
Back-up codes werken als eenmalige wachtwoorden. Je kunt ze altijd gebruiken in plaats van je gewone wachtwoord (bijvoorbeeld als je het bent vergeten), maar slechts één keer.

2024-11-14 09:23 UTC, Stokkie64 commented on client/src/lang/translations/nl.json
> +  "copy-to-clipboard-successful": "Back-up codes succesvol gecopieerd",
gekopieerd

2024-11-14 09:23 UTC, Stokkie64 commented on client/src/lang/translations/nl.json
> +  "import-data-description": "Selecteer je (eerder geëxporteerde) ZIP-bestand om de gegevens te uploaden. De teksten in het bestand worden behandeld als de nieuwste items. Het importeren kan een paar
Selecteer je (eerder geëxporteerde) ZIP-bestand om gegevens te uploaden. De teksten worden als nieuwste items behandeld. Importeren kan enkele minuten duren, afhankelijk van de bestandsgrootte.

2024-11-14 09:57 UTC, mhartgring commented
Good eye, I rushed into making this. I'll update the PR asap.

2024-11-14 10:19 UTC, ArjenMarcoSingels approved these changes
Akkoord, Happy with the language. I leave it to @PhiTux to merge this if he's happy :)

2024-11-14 10:29 UTC, Stokkie64 approved these changes
Approved, @PhiTux I approved with my incorrect github account. Are you able to remove that approval?

2024-11-14 14:08 UTC, PhiTux commented
Hi, 
thanks very much to everybody involved for the translation! 
I'm not exactly sure right now, if I will "just" try to update dailyTxT within the next days and integrate you translation into this, or if I should start to rewrite the whole thing. 
There are several new ideas now in the issues-section, that I would like to address. But I would then combine this with a rewrite...
Well, let's see...

2024-11-14 14:09 UTC, PhiTux commented
@Stokkie64 I'm not sure how I could remove you other approval. You mean the one right in front of the second approval, where you wrote this, right?

2024-11-14 14:18 UTC, Stokkie64 commented
I wouldn't stress about removing it but Thanks.

2024-11-14 14:40 UTC, merged

2024-11-16 17:04 UTC, PhiTux commented
Just for your interest: I'm planing to start a rewrite of dailytxt within the next days. I'll try to address most of the open issues within this step. The dutch translation will be included into this (although there will surely be several new text-snippets which need to be translated...)